# Generated by Django 3.2.16 on 2022-11-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0002_webpages_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpages',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='webpages',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='webpages',
            name='url',
            field=models.SlugField(),
        ),
    ]
