# Generated by Django 3.2.16 on 2022-11-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0003_auto_20221101_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpages',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
